name: Auto Commit Changes

on:
  schedule:
    - cron: "*/2 * * * *" # 每两分钟执行一次
  push:
    branches:
      - main # 你可以根据需要更改分支名称
  workflow_dispatch: # 新增手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # 选择合适的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          USER_ACCOUNT: ${{ secrets.USER_ACCOUNT }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          FEISHU_BOT_URL: ${{ secrets.FEISHU_BOT_URL }}
          FEISHU_BOT_SECRET: ${{ secrets.FEISHU_BOT_SECRET }}
        run: python main.py

      - name: Check for changes
        id: check_changes
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.CHANGES == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 刷新成绩
